// @app/client/app/components/PasswordStrength.tsx
import classNames from "classnames";
import { HiOutlineInformationCircle } from "react-icons/hi";

export interface PasswordStrengthProps {
  passwordStrength: number; // 0-4
  suggestions: string[];
  isDirty: boolean;
}

export function PasswordStrength({
  passwordStrength,
  suggestions = [
    "Use a few words, avoid common phrases",
    "No need for symbols, digits, or uppercase letters",
  ],
  isDirty = false,
}: PasswordStrengthProps) {
  if (!isDirty) return null;

  return (
    <div className="flex flex-row justify-between">
      <div className="basis-3/4">
        <progress
          className={classNames(
            ["progress progress-primary my-2 w-full"],
            passwordStrength < 2 ? "progress-error" : "progress-success"
          )}
          value={passwordStrength + 1}
          max="5"
        ></progress>
      </div>
      {suggestions.length > 0 && (
        <div className="dropdown dropdown-end dropdown-hover">
          <label
            tabIndex={0}
            className="btn btn-circle btn-ghost btn-xs text-info text-lg"
          >
            <HiOutlineInformationCircle />
          </label>
          <div
            tabIndex={0}
            className="card compact dropdown-content bg-base-100 rounded-box w-80 shadow"
          >
            <div className="card-body">
              <h2 className="card-title">Password Suggestions</h2>
              <ul className="list-inside list-disc">
                {suggestions.map((suggestion, key) => {
                  return <li key={key}>{suggestion}</li>;
                })}
              </ul>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// @app/client/src/lib/components/PasswordStrength.svelte
<script lang="ts">
  import { popup, ProgressBar } from "@skeletonlabs/skeleton";
  import zxcvbn from "zxcvbn";

  import IonInformationCircleOutline from "~icons/ion/information-circle-outline";

  function calculatePasswordStrength(password: string) {
    const { score, feedback } = zxcvbn(password || "");

    const messages = [...feedback.suggestions];
    if (feedback.warning !== "") {
      messages.push(feedback.warning);
    }
    return { score, messages };
  }

  export let passwordText: string;
  export let isDirty: boolean;

  let score = 0;
  let messages: string[] = [];

  $: ({ score, messages } = calculatePasswordStrength(passwordText));
</script>

<div class="flex flex-row items-center justify-between">
  <div class="basis-3/4">
    <ProgressBar
      label="Password Strength"
      value={score + 1}
      max={5}
      meter={score < 2 ? "bg-error-500" : "bg-success-500"}
      class={isDirty && passwordText !== "" ? "visible" : "invisible"}
    />
  </div>
  <div
    class="card variant-filled-warning z-[999] whitespace-nowrap p-2"
    data-popup="passwordSuggestionTooltip"
  >
    <div class="card-body">
      <h2 class="card-title">Password Suggestions</h2>
      <ul class="list-inside list-disc">
        {#each messages as message}
          <li>{message}</li>
        {/each}
      </ul>
    </div>
    <!-- Arrow -->
    <div class="arrow variant-filled-warning" />
  </div>
  <span
    use:popup={{
      event: "hover",
      target: "passwordSuggestionTooltip",
      placement: "bottom",
    }}
    class={isDirty && passwordText !== "" && messages.length > 0
      ? "visible"
      : "invisible"}
  >
    <IonInformationCircleOutline />
  </span>
</div>
