// @app/client/src/routes/(app)/(require-unauth)/forgot/+page.svelte
<script lang="ts">
  import { ProgressRadial } from "@skeletonlabs/skeleton";
  import { onDestroy } from "svelte";
  import type { z } from "zod";

  import { browser } from "$app/environment";
  import { page } from "$app/stores";
  import Alert from "$lib/components/Alert.svelte";
  import { createValidatedForm } from "$lib/form/createValidatedForm";
  import TextInput from "$lib/form/TextInput.svelte";
  import type { FailResult, FormError } from "$lib/utils/validate";

  import { forgotSchema } from "./schema";

  const { form, errors, setErrors, isSubmitting } =
    createValidatedForm<typeof forgotSchema>(forgotSchema);

  let formError: FormError | undefined = undefined;

  onDestroy(
    page.subscribe(({ form }) => {
      if (form?.fieldErrors || form?.formError) {
        const failResult = form as FailResult<
          z.infer<typeof forgotSchema>,
          typeof forgotSchema
        >;
        formError = failResult.formError;
        if (failResult.fieldErrors) {
          setErrors(failResult.fieldErrors);
        }
      }
    })
  );
</script>

<form
  method="POST"
  use:form
  class="flex w-full max-w-lg flex-col gap-y-5 p-2 lg:p-4"
>
  <TextInput
    name="email"
    placeholder="E-mail"
    type="email"
    autocomplete="email"
    error={browser ? $errors.email : $page.form?.fieldErrors?.email}
    value={browser ? undefined : $page.form?.values?.email}
    data-cy="forgotpage-input-email"
  />
  {#if formError}
    <Alert
      alertType="error"
      title="Forgot password failed"
      message={formError.message}
      code={formError.code}
    />
  {/if}
  <button
    type="submit"
    class="btn variant-filled-primary"
    disabled={$isSubmitting}
    data-cy="loginpage-button-submit"
  >
    {#if $isSubmitting}
      <div class="mr-2 h-6 w-6">
        <ProgressRadial />
      </div>
    {/if}Reset password</button
  >
  <a class="link self-center" href="/login">
    Remembered your password? Log in.
  </a>
</form>

// @app/client/app/routes/__index/forgot.tsx
import { getCodeFromError } from "@app/lib";
import type { ActionArgs, LoaderArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import { Link, useActionData } from "@remix-run/react";
import { redirect } from "@remix-run/server-runtime";
import { withZod } from "@remix-validated-form/with-zod";
import { IoPersonOutline } from "react-icons/io5";
import { AuthenticityTokenInput } from "remix-utils";
import { ValidatedForm, validationError } from "remix-validated-form";
import * as z from "zod";

import { ErrorAlert, FormInput, SubmitButton } from "~/components";
import { validateCsrfToken } from "~/utils/csrf";
import type { GraphqlQueryErrorResult } from "~/utils/errors";
import { requireNoUser } from "~/utils/users";

export const handle = { hideLogin: true, title: "Forgot Password" };

export const loader = async ({ context }: LoaderArgs) => {
  await requireNoUser(context);
  return null;
};

export const action = async ({ request, context }: ActionArgs) => {
  await validateCsrfToken(request, context);
  const sdk = await context.graphqlSdk;
  const fieldValues = await forgotPasswordFormValidator.validate(
    await request.formData()
  );
  if (fieldValues.error) {
    return validationError(fieldValues.error, {
      email: fieldValues.submittedData.email,
    });
  }
  const { email } = fieldValues.data;
  try {
    await sdk.ForgotPassword({ email });
    return redirect(`/forgot/success?email=${encodeURIComponent(email)}`);
  } catch (e: any) {
    const code = getCodeFromError(e);
    return json<GraphqlQueryErrorResult>({
      message: e.message,
      code,
      error: true,
    });
  }
};

const forgotPasswordSchema = z.object({
  email: z
    .string()
    .nonempty("Please input your E-mail.")
    .email("The input is not valid E-mail."),
});

const forgotPasswordFormValidator = withZod(forgotPasswordSchema);

export default function ForgotPassword() {
  const { message, code, error } =
    useActionData<GraphqlQueryErrorResult>() ?? {};

  return (
    <ValidatedForm
      validator={forgotPasswordFormValidator}
      method="post"
      className="flex w-full max-w-lg flex-col gap-y-5"
    >
      <AuthenticityTokenInput />
      <FormInput
        name="username"
        placeholder="Email"
        required
        type="email"
        autoComplete="email"
        inputPrefix={<IoPersonOutline />}
      />
      {error ? (
        <ErrorAlert title="Login failed" message={message} code={code} />
      ) : null}

      <div className="align-center flex justify-between">
        <SubmitButton data-cy="loginpage-button-submit">
          Reset password
        </SubmitButton>
        <Link className="link self-center" to="/login">
          Use a different sign in method
        </Link>
      </div>

      <Link className="link" to="/login/email">
        Remembered your password? Log in.
      </Link>
    </ValidatedForm>
  );
}
