// @app/client/src/routes/(app)/(require-unauth)/register/+page.svelte
<script lang="ts">
  import { popup, ProgressRadial } from "@skeletonlabs/skeleton";
  import { onDestroy } from "svelte";
  import type { z } from "zod";

  import IonHelpCircleOutline from "~icons/ion/help-circle-outline";
  import { browser } from "$app/environment";
  import { page } from "$app/stores";
  import Alert from "$lib/components/Alert.svelte";
  import PasswordStrength from "$lib/components/PasswordStrength.svelte";
  import { createValidatedForm } from "$lib/form/createValidatedForm";
  import TextInput from "$lib/form/TextInput.svelte";
  import { isSafe } from "$lib/utils/uri";
  import type { FailResult, FormError } from "$lib/utils/validate";

  import { registerSchema } from "./schema";

  $: rawNext = $page.url.searchParams.get("next");
  $: next = isSafe(rawNext) ? rawNext : "/";

  const { form, errors, setErrors, isSubmitting } =
    createValidatedForm<typeof registerSchema>(registerSchema);

  let formError: FormError | undefined = undefined;

  let passwordText = "";
  let passwordDirty = false;
  function onPasswordChange(event: Event) {
    const target = event.target as HTMLInputElement;
    passwordText = target.value;
    passwordDirty = true;
  }

  onDestroy(
    page.subscribe(({ form }) => {
      if (form?.fieldErrors || form?.formError) {
        const failResult = form as FailResult<
          z.infer<typeof registerSchema>,
          typeof registerSchema
        >;
        formError = failResult.formError;
        if (failResult.fieldErrors) {
          setErrors(failResult.fieldErrors);
        }
      }
    })
  );
</script>

<form
  method="POST"
  use:form
  class="flex w-full max-w-lg flex-col gap-y-2 p-2 lg:p-4"
>
  <input type="hidden" name="next" value={next} />
  <TextInput
    name="name"
    required
    type="text"
    autocomplete="name"
    error={browser ? $errors.name : $page.form?.fieldErrors?.name}
    value={browser ? undefined : $page.form?.values?.name}
    data-cy="registerpage-input-name"
  >
    <svelte:fragment slot="label">
      <span data-cy="registerpage-name-label" class="flex items-center">
        Name&nbsp;
        <span
          use:popup={{
            event: "hover",
            target: "nameTooltip",
            placement: "top",
          }}
        >
          <IonHelpCircleOutline />
        </span>
        <div
          class="card variant-filled-primary z-[999] whitespace-nowrap p-2 text-center text-xs shadow-xl"
          data-popup="nameTooltip"
        >
          What is your name?
          <!-- Arrow -->
          <div class="arrow variant-filled-primary" />
        </div>
      </span>
    </svelte:fragment>
  </TextInput>
  <TextInput
    name="username"
    autocomplete="username"
    error={browser ? $errors.username : $page.form?.fieldErrors?.username}
    value={browser ? undefined : $page.form?.values?.username}
    data-cy="registerpage-input-username"
  >
    <svelte:fragment slot="label"
      ><span data-cy="registerpage-username-label" class="flex items-center">
        Username&nbsp;
        <span
          use:popup={{
            event: "hover",
            target: "usernameTooltip",
            placement: "top",
          }}
        >
          <IonHelpCircleOutline />
        </span>
        <div
          class="card variant-filled-primary whitespace-nowrap p-2 text-center text-xs shadow-xl"
          data-popup="usernameTooltip"
        >
          What do you want others to call you?
          <!-- Arrow -->
          <div class="arrow variant-filled-primary" />
        </div>
      </span></svelte:fragment
    >
  </TextInput>
  <TextInput
    name="email"
    autocomplete="email"
    error={browser ? $errors.email : $page.form?.fieldErrors?.email}
    value={browser ? undefined : $page.form?.values?.email}
    data-cy="registerpage-input-email"
  >
    <svelte:fragment slot="label">E-mail</svelte:fragment>
  </TextInput>
  <TextInput
    name="password"
    type="password"
    autocomplete="new-password"
    error={browser ? $errors.password : $page.form?.fieldErrors?.password}
    on:input={onPasswordChange}
    data-cy="registerpage-input-password"
  >
    <svelte:fragment slot="label">Passphrase</svelte:fragment>
    <svelte:fragment slot="content">
      <PasswordStrength {passwordText} isDirty={passwordDirty} />
    </svelte:fragment>
  </TextInput>
  <TextInput
    name="confirm"
    type="password"
    autocomplete="new-password"
    error={browser ? $errors.confirm : $page.form?.fieldErrors?.confirm}
    data-cy="registerpage-input-password2"
  >
    <svelte:fragment slot="label">Confirm Passphrase</svelte:fragment>
  </TextInput>
  <div class="flex items-center justify-between">
    <button
      type="submit"
      class="btn variant-filled-primary"
      disabled={$isSubmitting}
      data-cy="registerpage-submit-button"
    >
      {#if $isSubmitting}
        <div class="mr-2 h-6 w-6">
          <ProgressRadial />
        </div>
      {/if}Create Account</button
    >

    <a class="link self-center" href="/login">
      Use a different sign in method
    </a>
  </div>
  {#if formError}
    <Alert
      alertType="error"
      title="Account creation failed"
      message={formError.message}
      code={formError.code}
    />
  {/if}
</form>

// @app/client/app/routes/__index/register.tsx
import { getCodeFromError } from "@app/lib";
import type { ActionArgs, LoaderArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import { useActionData, useSearchParams } from "@remix-run/react";
import { redirect } from "@remix-run/server-runtime";
import { withZod } from "@remix-validated-form/with-zod";
import { useState } from "react";
import { HiOutlineQuestionMarkCircle, HiOutlineXCircle } from "react-icons/hi";
import { AuthenticityTokenInput } from "remix-utils";
import { ValidatedForm, validationError } from "remix-validated-form";
import * as z from "zod";

import { ErrorAlert, PasswordStrength } from "~/components";
import { FormInput } from "~/components/forms/FormInput";
import { SubmitButton } from "~/components/forms/SubmitButton";
import { validateCsrfToken } from "~/utils/csrf";
import type { GraphqlQueryErrorResult } from "~/utils/errors";
import { setPasswordStrengthInfo } from "~/utils/passwords";
import { isSafe } from "~/utils/uri";
import { requireNoUser } from "~/utils/users";

export const handle = { hideLogin: true, title: "Register" };

export const loader = async ({ context }: LoaderArgs) => {
  await requireNoUser(context);
  return null;
};

export const action = async ({ request, context }: ActionArgs) => {
  await validateCsrfToken(request, context);
  const sdk = await context.graphqlSdk;
  const fieldValues = await registerFormValidator.validate(
    await request.formData()
  );
  if (fieldValues.error) {
    return validationError(fieldValues.error, {
      username: fieldValues.submittedData.username,
    });
  }
  const { name, username, email, password, redirectTo } = fieldValues.data;
  try {
    await sdk.Register({ name, username, email, password });
    return redirect(redirectTo ?? "/");
  } catch (e: any) {
    const { password, confirm, ...restSubmittedValues } =
      fieldValues.submittedData;
    const code = getCodeFromError(e);
    if (code === "WEAKP") {
      return validationError(
        {
          fieldErrors: {
            password:
              "The server believes this passphrase is too weak, please make it stronger.",
          },
        },
        restSubmittedValues
      );
    }
    if (code === "EMTKN") {
      return validationError(
        {
          fieldErrors: {
            email:
              "An account with this email address has already been registered, consider using the 'Forgot passphrase' function.",
          },
        },
        restSubmittedValues
      );
    }
    if (code === "NUNIQ") {
      return validationError(
        {
          fieldErrors: {
            username:
              "An account with this username has already been registered, please try a different username.",
          },
        },
        restSubmittedValues
      );
    }
    if (code === "23514") {
      return validationError(
        {
          fieldErrors: {
            username:
              "This username is not allowed; usernames must be between 2 and 24 characters long (inclusive), must start with a letter, and must contain only alphanumeric characters and underscores.",
          },
        },
        restSubmittedValues
      );
    }
    return json<GraphqlQueryErrorResult>({
      message: e.message,
      code,
      error: true,
    });
  }
};

const registerSchema = z
  .object({
    name: z.string().nonempty("Please input your name."),
    username: z
      .string()
      .nonempty("Please input your username")
      .min(2, "Username must be at least 2 characters long.")
      .max(24, "Username must be no more than 24 characters long.")
      .regex(/^([a-zA-Z]|$)/, "Username must start with a letter.")
      .regex(
        /^([^_]|_[^_]|_$)*$/,
        "Username must not contain two underscores next to each other."
      )
      .regex(
        /^[a-zA-Z0-9_]*$/,
        "Username must contain only alphanumeric characters and underscores."
      ),
    email: z
      .string()
      .nonempty("Please input your E-mail.")
      .email("The input is not valid E-mail."),
    password: z.string().nonempty("Please input your passphrase."),
    confirm: z.string().nonempty("Please input your passphrase."),
    redirectTo: z.string().optional(),
  })
  .refine(({ password, confirm }) => password === confirm, {
    message: "Make sure your passphrase is the same in both passphrase boxes.",
    path: ["confirm"],
  });

const registerFormValidator = withZod(registerSchema);

export default function Register() {
  const [searchParams] = useSearchParams();
  const rawNext = searchParams.get("next");
  const next = isSafe(rawNext) ? rawNext : "/";

  const { message, code, error } =
    useActionData<GraphqlQueryErrorResult>() ?? {};

  const [passwordStrength, setPasswordStrength] = useState<number>(0);
  const [passwordSuggestions, setPasswordSuggestions] = useState<string[]>([]);
  const [passwordDirty, setPasswordDirty] = useState(false);

  return (
    <ValidatedForm
      validator={registerFormValidator}
      method="post"
      className="flex w-full max-w-lg flex-col gap-y-1"
      noValidate
    >
      <AuthenticityTokenInput />
      <input type="hidden" name="redirectTo" value={next} />
      <FormInput
        name="name"
        label={
          <span data-cy="registerpage-name-label" className="flex">
            Name&nbsp;
            <span
              className="tooltip flex w-5 items-center"
              data-tip="What is your name?"
            >
              <HiOutlineQuestionMarkCircle />
            </span>
          </span>
        }
        required
        type="text"
        autoComplete="name"
        data-cy="registerpage-input-name"
      />
      <FormInput
        name="username"
        label={
          <span className="flex">
            Username&nbsp;
            <span
              className="tooltip flex w-5 items-center"
              data-tip="What do you want others to call you?"
            >
              <HiOutlineQuestionMarkCircle />
            </span>
          </span>
        }
        required
        type="text"
        autoComplete="username"
        data-cy="registerpage-input-username"
      />
      <FormInput
        name="email"
        label="E-mail"
        required
        type="email"
        autoComplete="email"
        data-cy="registerpage-input-email"
      />
      <FormInput
        name="password"
        label="Passphrase"
        required
        type="password"
        onChange={(e) => {
          setPasswordStrengthInfo(
            e.target.value,
            setPasswordStrength,
            setPasswordSuggestions
          );
          setPasswordDirty(true);
        }}
        autoComplete="new-password"
        data-cy="registerpage-input-password"
      >
        <PasswordStrength
          passwordStrength={passwordStrength}
          suggestions={passwordSuggestions}
          isDirty={passwordDirty}
        />
      </FormInput>
      <FormInput
        name="confirm"
        label="Confirm passphrase"
        required
        type="password"
        autoComplete="new-password"
        data-cy="registerpage-input-password2"
      />
      {error ? (
        <ErrorAlert title="Registration failed" message={message} code={code} />
      ) : null}
      <div className="align-center flex justify-start">
        <SubmitButton data-cy="registerpage-submit-button">
          Register
        </SubmitButton>
      </div>
    </ValidatedForm>
  );
}
